### ISSUE TITLE
TODO: REST API

### ISSUE THREAD

**Issue by bennyn** [bennyn/coinbase-pro-node#17]
## Related projects
- https://github.com/ccxt/ccxt/blob/master/js/coinbasepro.js
- https://github.com/coinbase/coinbase-pro-node
- https://github.com/vansergen/coinbase-pro

#### Accounts
- [x] [List Accounts](https://docs.pro.coinbase.com/#list-accounts)
- [x] [Get an Account](https://docs.pro.coinbase.com/#get-an-account)
- [x] [Get Account History](https://docs.pro.coinbase.com/#get-account-history)
- [x] [Get Holds](https://docs.pro.coinbase.com/#get-holds)

#### Orders
- [x] [Place a New Order](https://docs.pro.coinbase.com/#place-a-new-order)
- [x] [Cancel an Order](https://docs.pro.coinbase.com/#cancel-an-order)
- [x] [Cancel all](https://docs.pro.coinbase.com/#cancel-all)
- [x] [List Orders](https://docs.pro.coinbase.com/#list-orders)
- [x] [Get an Order](https://docs.pro.coinbase.com/#get-an-order)

#### Fills
- [x] [List Fills](https://docs.pro.coinbase.com/#list-fills)

#### Deposits
- [ ] [Deposit funds from a payment method](https://docs.pro.coinbase.com/#payment-method)
- [ ] [Deposit funds from a coinbase account](https://docs.pro.coinbase.com/#coinbase)

#### Withdrawals
- [ ] [Withdraw funds to a payment method](https://docs.pro.coinbase.com/#payment-method46)
- [ ] [Withdraw funds to a coinbase account](https://docs.pro.coinbase.com/#coinbase47)
- [ ] [Withdraw funds to a crypto address](https://docs.pro.coinbase.com/#crypto)

#### Stablecoin Conversions
- [ ] [Create Conversion](https://docs.pro.coinbase.com/#stablecoin-conversions)

#### Payment Methods
- [ ] [List Payment Methods](https://docs.pro.coinbase.com/#list-payment-methods)

#### Coinbase Accounts
- [ ] [List Accounts](https://docs.pro.coinbase.com/#list-accounts54)

#### Fees
- [ ] [Get Current Fees](https://docs.pro.coinbase.com/#get-current-fees)

#### Reports
- [ ] [Create a new report](https://docs.pro.coinbase.com/#create-a-new-report)
- [ ] [Get report status](https://docs.pro.coinbase.com/#get-report-status)

#### Profiles
- [x] [List Profiles](https://docs.pro.coinbase.com/#list-profiles)
- [x] [Get a Profile](https://docs.pro.coinbase.com/#get-a-profile)
- [x] [Create profile transfer](https://docs.pro.coinbase.com/#create-profile-transfer)

#### User Account
- [x] [Trailing Volume](https://docs.pro.coinbase.com/#trailing-volume)

#### Products
- [x] [Get Products](https://docs.pro.coinbase.com/#get-products)
- [x] [Get Product Order Book](https://docs.pro.coinbase.com/#get-product-order-book)
- [x] [Get Product Ticker](https://docs.pro.coinbase.com/#get-product-ticker)
- [x] [Get Trades](https://docs.pro.coinbase.com/#get-trades)
- [x] [Get Historic Rates](https://docs.pro.coinbase.com/#get-historic-rates)
- [x] [Get 24hr Stats](https://docs.pro.coinbase.com/#get-24hr-stats)

#### Currencies
- [ ] [Get currencies](https://docs.pro.coinbase.com/#get-currencies)

#### Time
- [x] [Get time](https://docs.pro.coinbase.com/#time)
